// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateQuote(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string,arg6:number,arg7:number,arg8:string,arg9:number,arg10:number,arg11:string,arg12:Array<string>,arg13:string):Promise<string>;

export function GetCurrentParameterVersion():Promise<string>;

export function GetParameterSet():Promise<string>;

export function GetParameterVersions():Promise<Array<Record<string, any>>>;

export function LoadParameterSet(arg1:string):Promise<void>;

export function RefreshParameters():Promise<void>;

export function UpdateParameterSet(arg1:string):Promise<void>;
