// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateQuote(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['CalculateQuote'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function GetCurrentParameterVersion() {
  return window['go']['main']['App']['GetCurrentParameterVersion']();
}

export function GetParameterSet() {
  return window['go']['main']['App']['GetParameterSet']();
}

export function GetParameterVersions() {
  return window['go']['main']['App']['GetParameterVersions']();
}

export function LoadParameterSet(arg1) {
  return window['go']['main']['App']['LoadParameterSet'](arg1);
}

export function RefreshParameters() {
  return window['go']['main']['App']['RefreshParameters']();
}

export function UpdateParameterSet(arg1) {
  return window['go']['main']['App']['UpdateParameterSet'](arg1);
}
