name: Package One-Click App

on:
  workflow_dispatch: {}

jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.403'

      - name: Install MAUI workload (for XAML toolchain)
        run: |
          dotnet workload install maui-windows

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Package One-Click (self-contained)
        shell: pwsh
        run: |
          ./scripts/package-oneclick.ps1 -Configuration Release -Runtime win-x64

      - name: Upload One-Click artifact
        uses: actions/upload-artifact@v4
        with:
          name: oneclick-win-x64
          path: artifacts/oneclick/win-x64
